Nez-PCL/ECS/Components/Physics/CircleCollider.cs
Pushed to master instead of a new branch; this one is on its own branch in case you want to close the other pull request.
=> fixed circle collider shape not being set in CircleCollider constructor

Nez.PipelineImporter/Tiled/TiledMapProcessor.cs
=> Fixed Color.FromArgb

Nez-PCL/Math/Mathf.cs
=> added inverse lerp

Nez-PCL/ECS/Components/Text/FramesPerSecondCounter.cs
Added dockOffset to allow you to dictate how far from the screen edges the fps text will appear.
Changing dockPosition after the class has been instantiated will now properly update the position of the fps text.
Added fluent setters for dockPosition and dockOffset.
=> Added offset. Fixed dock position.

Nez-PCL/ECS/Components/FollowCamera.cs
Camera would revert to default style after being added to an entity.
=> Camera fix

Nez-PCL/ECS/Components/Renderables/RenderableComponent.cs, Nez-PCL/ECS/InternalUtils/RenderableComponentList.cs
=> Fixed render layer component lists not updating

Nez.PipelineImporter/Tiled/TiledMapWriter.cs
=> largestTile written as float while it should be int

Nez.PipelineImporter/Tiled/TmxObject.cs
fix for systems where decimal separator is not dot "."
=> Fix NumberFormat error

Nez-PCL/Graphics/Batcher/GraphicsResource.cs
=> Fix minor spelling error

Nez.Portable/Graphics/Batcher/Batcher.cs, Nez.Portable/UI/Drawable/SubtextureDrawable.cs
=> SpriteEffects for UI SubtextureDrawable

Nez.FarseerPhysics/Nez/Common/FSWorld.cs
TimeRuler is only available in debug configuration.
=> Fix FarseerPhysics not compiling in release mode

Nez.Portable/ECS/Entity.cs
Currently it is not possible to override Entity.clone for customizing clone behavior.
=> Mark Entity.clone as virtual to allow overriding

Nez.Portable/AI/BehaviorTree/BehaviorTreeBuilder.cs
I'm adding this so that I can use the behavior tree builder to create a behavior tree with a non-default update period.
=> Add optional 'updatePeriod' parameter to 'build' method

Nez.Portable/ECS/InternalUtils/EntityList.cs
This is the fix for issue #207.
=> fix leaking internal tag list to outside objects

Nez.Portable/ECS/Components/ColorCycler.cs, Nez.Portable/Graphics/Textures/TextureUtils.cs, Nez.Portable/UI/Base/Group.cs, Nez.Portable/UI/Containers/Container.cs, Nez.Portable/UI/Containers/ScrollPane.cs, Nez.Portable/UI/Containers/SplitPane.cs, Nez.Portable/UI/Containers/Table.cs, Nez.Portable/UI/Widgets/Image.cs, Nez.Portable/UI/Widgets/Label.cs, Nez.Portable/UI/Widgets/ListBox.cs, Nez.Portable/UI/Widgets/ProgressBar.cs, Nez.Portable/UI/Widgets/SelectBox.cs, Nez.Portable/UI/Widgets/TextField.cs, Nez.Portable/UI/Widgets/Window.cs, Nez.Portable/Utils/Extensions/ColorExt.cs, Nez.Portable/Utils/Tweens/Easing/Lerps.cs
Sorry for the long delay; I was planning to test every individual case, but at this rate, I'm never going to get around to it. The changes were fairly mechanical, and I tested at least one of each type. Feel free to reject this pull request if that doesn't seem rigorous enough.
=> Color Multiplication Bugs

Nez.Portable/Math/Random.cs
Just thought the Random class needed a way to get/set the current seed.
I'm using 'Environment.TickCount' as the initial seed because that seems to be what the default implementation is.  [http://referencesource.microsoft.com/#mscorlib/system/random.cs,bb77e610694e64ca](http://referencesource.microsoft.com/#mscorlib/system/random.cs,bb77e610694e64ca)
I also merged the three separate 'choose' functions into a single function that allows for an arbitrary number of parameters.
=> Add seed management and cleanup for Random

Nez.Portable/Utils/Extensions/ListExt.cs
This was something I needed and thought it would be a useful extension to add for everyone.
=> new method to get more than one random item from a list

Nez.Portable/ECS/InternalUtils/RenderableComponentList.cs
=> Fixes bug where renderables added by a component can cause a crash

Nez.Portable/Nez.csproj, Nez.Portable/UI/Base/Group.cs, Nez.Portable/UI/Base/ICullable.cs, Nez.Portable/UI/Containers/ScrollPane.cs
When using a ScrollPane, culling will help rendering a Group with lot of items (ex a ListView widget)
I just copied how libGDX did it
=> Implemented missing Cullable feature

Nez.Portable/Input/Input.cs
=> Added support for middle button

Nez.Portable/ECS/InternalUtils/EntityList.cs
#314 
I was curious about this. So I decided to move forward with it. Do the changes make sense if we change these to Lists to HashSets?
=> Converted EntityList toRemove and toAdd Lists to HashSets

Nez.Portable/Utils/DebugConsole/DebugConsole.cs
=> Made console key configurable

Nez.Portable/UI/Widgets/Window.cs
=> Added missing clamp check to window movement

README.md
Resolves #247. I even got caught by this myself when setting up a test project recently.
=> Fixed some newbie gotchas in readme setup

Nez.Portable/ECS/Components/Physics/ArcadeRigidbody.cs
=> Colliders on the same entity can no longer collide

Nez.Portable/Physics/ColliderTriggerHelper.cs
=> Fixed a crash when a collision pair of entities destroy themselves

Nez.Portable/ECS/InternalUtils/EntityList.cs
It was returning the wrong entities.
=> Bug fix for 'entitiesWithTag'

Nez.Portable/Math/RectangleF.cs
returns a rectangle of the area where the two rectangles overlap.  It's like the opposite of union.
=> Add overlap to RectangleF

Nez.Portable/AI/Pathfinding/AStar/AstarGridGraph.cs
allow modifying the possible movement directions (for example, diagonal movement) in `AstarGridGraph`
=> allow modifiable directions

Nez.Portable/UI/Containers/TabPane.cs
=> Added TabPane

Nez.Portable/UI/Containers/Tree.cs
=> Added Tree/Node container

Nez.Portable/PipelineRuntime/TextureAtlas/TextureAtlasReader.cs
A minor fix for NinePatchSubtexture loading in TextureAtlasReader
=> Correct loading of 9patch textures

Nez.ImGui/Core/ImGuiManager.Impl.cs, Nez.ImGui/Core/ImGuiManager.cs, Nez.ImGui/Core/ImGuiOptions.cs, Nez.ImGui/Core/ImGuiRenderer.cs
. Allow the caller to specify the title of the Game Window.
. Allow the caller to specify the first position of the Game Window.
. Allow the caller to add ImGuiWindowFlags to the Game Window.
(all of the above via fluent setters)
. Add a showMenuBar boolean control to ImGuiManager to control drawing of the MenuBar in the IM GUI window.
=> Add additional options to the ImGuiOptions class to support further customization

Nez.Portable/Nez.FNA.Standard.csproj
This will allow for .net Core projects to use Nez
=> Added in a .Net standard compatible project file

Nez.Portable/Nez.FNA.Standard.csproj
As I progressed with a .net Core project I encountered issues that I did not foresee in my first PR.
These have now been resolved and I apologise for not doing a thorough check
=> Minor fixes

Nez.Portable/Input/Input.cs, Nez.Portable/Utils/Fonts/NezSpriteFont.cs, Nez.Portable/Utils/NezContentManager.cs
The PascalCase branch wasn't building due to incorrect function names. Changed function names to PascalCase and now project builds.
=> Change some more function names to PascalCase

Nez.Portable/Utils/DebugConsole/DebugConsole.cs
Added support for moving the underscore along in the console, inserts/removes the character at the underscore
=> Added support for moving underscore on console

Nez.Portable/UI/Widgets/NumberField.cs
Has minor sizing issues.
It's a number field that allows you to increase, decrease numbers with by pressing plus or minus, mouse scroll, or plain input. It limits the numbers between the set min and max.
=> NumberField element

Nez.Portable/Core.cs, Nez.Portable/Debug/Console/DebugConsole.cs, Nez.Portable/Debug/Console/DefaultCommands.cs, Nez.Portable/Utils/Analysis/TimeRuler.cs
Need to disable input to UI and game based on this as the DebugConsole input doesn't really go through my (or anyones) input handler right now.
=> DebugConsole IsOpen to public

Nez.Portable/Assets/Tiled/TiledTypes/Tileset.cs
If you delete a tile from an image collection it creates a hole in the id counter, otherwise it messes up your map so we can't use a for loop here like this.
=> Can't assume that image collection tile Id exists

Nez.Portable/Assets/Tiled/TiledTypes/Map.cs
Core. StartSceneTransition throw image null
=> Tiled Dispose Image NULL

Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
Excuse me, but my last [PR](https://github.com/prime31/Nez/pull/535) worked only for PingPong animations with 3 frames. This PR fixes it to work for ones with any frames.
=> Fixed PingPong animation (again) #532

Nez.Portable/Physics/Shapes/Polygon.cs
The offset angle has to be calculated with the scaled offset.
=> Fixed offsetAngle for rotated polygon colliders

Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
The picture shows how the fix works:
=> Fixed PingPongOnce animation

Nez.Portable/Graphics/Batcher/Batcher.cs
=> Fixed reduced performance resulting from performance boost

Nez.Portable/Assets/Tiled/Runtime/TiledRendering.cs
Enable rendering of Tiled map Tile and Text objects.
=> Fix Tile and Text object rendering

Nez.Portable/Graphics/Textures/Sprite.cs
Returns the correct amount of sprites from the SpritesFromAtlas function.
=> Fix Issue #530

Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
=> fix large tile detection (2)

Nez.FarseerPhysics/Nez/HighLevel/Components/FSRigidBody.cs, Nez.FarseerPhysics/Nez/HighLevel/Components/Joints/FSMouseJoint.cs, Nez.FarseerPhysics/Nez/LowLevel/Components/FSGenericBody.cs, Nez.FarseerPhysics/Nez/LowLevel/Components/Renderables/FSRenderableBody.cs, Nez.Portable/ECS/Components/CameraShake.cs, Nez.Portable/ECS/Components/ColorCycler.cs, Nez.Portable/ECS/Components/FollowCamera.cs, Nez.Portable/ECS/Components/Physics/ArcadeRigidbody.cs, Nez.Portable/ECS/Components/Renderables/Particles/ParticleEmitter.cs, Nez.Portable/ECS/Components/Renderables/SpringGrid.cs, Nez.Portable/ECS/Components/Renderables/Sprites/ScrollingSpriteRenderer.cs, Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs, Nez.Portable/ECS/Components/Renderables/Sprites/SpriteTrail.cs, Nez.Portable/ECS/Components/Renderables/TiledMapRenderer.cs, Nez.Portable/ECS/Components/Renderables/TrailRibbon.cs, Nez.Portable/ECS/Components/Renderables/UICanvas.cs, Nez.Portable/ECS/Components/Text/FramesPerSecondCounter.cs
Change signature of classes that implement  IUpdatable so that can be overriden by subclasses of classes implementing IUpdatable
=> Make iupdatable update public

FAQs/Physics.md
Minor things I just spotted - lack of '()' operators where method calls are supposed to be and not closed conditional.
=> Fix physics example code snippet

Nez.ImGui/Core/ImGuiManager.Impl.cs, Nez.ImGui/Inspectors/SceneGraphPanes/EntityPane.cs, Nez.ImGui/Nez.MG38.ImGui.csproj, Nez.ImGui/Tools/SpriteAtlasEditorWindow.cs, Nez.ImGui/Utils/NezImGui.cs
This reverts commit 2fd2735a688e6b3bf83404db15610bd75293d7a9 which only affects positively the Samples of the MG38 NET6 project.
A new PR should be done addressing FNA and MG37 if possible as well.
=> Revert "Bump ImGui.NET version (#712)"

Nez.Portable/Utils/Coroutines/CoroutineManager.cs
Added `ClearAllCoroutines()` method to allow a CoroutineManager to be reset/reused. Useful if you want to attach a CoroutineManager to an entity or component.
Also, you can now yield IEnumerator types from coroutines. The CoroutineManager will automatically identify it and wrap it inside a `StartCoroutine()` call. (less code to write yay!)
Example usage:
```csharp
public IEnumerator ExamplePause()
{
float timer = 5f;
while(timer > 0) {
timer -= Time.DeltaTime;
yield return null;
}
}
public IEnumerator MyCoroutine()
{
// this is now valid:
yield return ExamplePause();
// in addition to the old way:
yield return _myCoroutineManager.StartCoroutine(ExamplePause());
}
```
=> Add ClearAllCoroutines() and allow yielding IEnumerator from coroutines

Nez.Portable/Utils/Tweens/TweenManager.cs
I'm not sure if the function I created called "AllTweensWithTargetEntity" breaks any rules, if it does I can remove it and just move it into my game's code.
=> Added Active Tween Accessor

Nez.Portable/ECS/Components/Text/FramesPerSecondCounter.cs
=> Fix FramesPerSecondCounter to render in screen space

Nez.Portable/Debug/Console/DebugConsole.cs
fixed key repeat counters to make the debug console usable on scaled time
=> fixed key repeat counters to make the console usable on scaled time

Nez.Portable/ECS/Camera.cs
Addresses #754 
Was missing the rotation part.
If you are amenable, I'd also like to make ViewMatrix3d and ProjectionMatrix3d virtual, to support other types of 3d cameras.
For example, I've currently got a camera subclass that is running an orthographic projection.
LMK your opinion and I will either add to this pr or open a new one.
=> Add rotation matrix to camera ViewMatrix3D

Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
Noticed that TiledMapLoader does not support template objects, and that's a useful feature so I decided to add it.
When loading an object it checks for a `template` attribute. If it's not null it the proceeds to load that template file, getting all the relevant object data from there.
It also supports overriding.
=> Object template support for TiledMapLoader

Nez.Portable/Utils/Coroutines/CoroutineManager.cs
Added StopAllCoroutines() method, which will stop all of a manager's coroutines, and can be safely called from inside one of the manager's running coroutines.
ClearAllCoroutines() will now throw an exception if it's called from inside a coroutine, since this can cause unstable behavior.
=> Add StopAllCoroutines() method

Nez.github.io/src/pages/index.js, Nez.github.io/src/pages/styles.module.css
Merge in external api docs button
=> external api docs button on website

FAQs/lang.cn_wip/ContentManagement.md, FAQs/lang.cn_wip/DearImGui.md, FAQs/lang.cn_wip/DeferredLighting.md, FAQs/lang.cn_wip/EntitySystems.md, FAQs/lang.cn_wip/FNACompat.md, FAQs/lang.cn_wip/Nez-Core.md, FAQs/lang.cn_wip/Physics.md, FAQs/lang.cn_wip/Rendering.md, FAQs/lang.cn_wip/RuntimeInspector.md, FAQs/lang.cn_wip/SVG.md, FAQs/lang.cn_wip/Samples.md, FAQs/lang.cn_wip/Scene-Entity-Component.md, FAQs/lang.cn_wip/SceneTransitions.md, README.cn.md, README.md
translate few docs into chinese
=> translate few docs into chinese

README.md
Added link to Nez's docs directly into the README, which allows users to use <Ctrl><F> to quickly find them.
=> Added direct link to docs

Nez.Portable/AI/FSM/SimpleStateMachine.cs
allows you to change the state from anywhere
=> public access to CurrentState in SimpleStateMachine

Nez.Portable/ECS/Entity.cs, Nez.Portable/Utils/Extensions/ComponentExt.cs
missed this stuff in the extension class
=> Few leftovers for Interfaces via GetComponent

Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
Fix for https://github.com/prime31/Nez/issues/799
=> Fix for issue 799. Last uid is now also read.

Nez.Portable/ECS/Components/Physics/ArcadeRigidbody.cs
fixed it so the ArcadeRigidbody wont check for collision with "Triggers" or if the RigidBody itself has a Trigger collider
=> Update ArcadeRigidbody.cs missed if for IsTrigger checks.

Nez.Portable/UI/Stage.cs
This sets the element to null and also sets the enable to false
=> Add method to disable gamepad focus- Stage.cs

Nez.Portable/ECS/Components/Physics/TiledMapMover.cs
make working this old code used for showing which tiles the mover is interested in.
=> update DEBUG_MOVER for Pascal-casing TiledMapMover.cs

Nez.Portable/Graphics/Effects/EffectResource.cs, Nez.Portable/Graphics/Effects/InvertEffect.cs
this Nez effect exists but there was no class or loading in place for it.
I tested it on a sprite and it worked fine..
=> reintroduce the InvertEffect

Nez.Portable/Assets/Aseprite/AsepriteFile.cs
convenient way to quickly get a texture from a frame number
=> add method to get a single texture - AsepriteFile.cs

Nez.Portable/Assets/Tiled/TiledTypes/TiledCore.cs
After commit #797 which improved tiled map loading performance, several compressed maps were failing to load.  Tracked the issue down to the decompression code failing to properly restore the data in some cases.  Not entirely sure why, but reworking the decompression approach a bit fixes the issue.
=> Fix for decompressing Tiled maps

Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
these are convenient to have. added new public property getters
=> add public fields for elapsedTime and loopMode

Nez.Portable/ECS/Components/Renderables/Sprites/SpriteRenderer.cs
Added instance methods to SetFlipXAndAdjustLocalOffset and SetFlipYAndAdjustLocalOffset to allow for flipping AND adjusting the offset to account for the flip.
=> Added SetFlipXAndAdjustLocalOffset and SetFlipYAndAdjustLocalOffset to SpriteRenderer

Nez.Portable/Math/RectangleF.cs
Hi
RectangleF  has a Max property which gets the max point of the rectangle, the bottom-right corner, Vector2(Right, Bottom)
I added a Min property to RectangleF gets the min point of the rectangle, the top-left corner, Vector2(Left, Top)
=> add Min to RectangleF

Nez.ImGui/Inspectors/ObjectInspectors/SceneComponentInspector.cs, Nez.ImGui/Inspectors/SceneGraphPanes/SceneComponentsPane.cs, Nez.ImGui/Inspectors/SceneGraphWindow.cs
this adds a new section to the imguimanager to view the current SceneComponents just like PostProcessors and Renderers sections.
=> add SceneComponent pane to ImGuiManager

Nez.Portable/Assets/Aseprite/AsepriteFile.cs
this method I added recently worked fine, but I was bothered by a poor choice in the variable name
=> AsepriteFile - better variable name for new method

Nez.Portable/UI/Stage.cs
SecondaryInputPressed but UpdatePrimaryInputDown
=> Fix SecondaryInputPressed but invoke UpdatePrimaryInputDown
