prime31/Nez

- Nez.PipelineImporter/Tiled/TmxDataTile.cs
"cannot be serialized because it does not have a parameterless constructor"
> Change back TmxDataTile

- Nez-PCL/ECS/Components/Renderables/TrailRibbon.cs
Overrode onEnable to clear segments and re-initialize vertices so trail would reset when needed. This is useful when trail is attached to Pooled entity
#46 #
> TrailRibbon update to behave better when attached to pooled entity

- Nez-PCL/UI/Containers/ScrollPane.cs
- Nez-PCL/UI/Containers/SplitPane.cs
- Nez-PCL/UI/Stage.cs
If the UI was being rendered by a ScreenSpaceRenderer and the scene had a different camera, then the ScissorStack would generate the clipping rectangle from the wrong camera.
> UI clipping fixes

- Nez-PCL/ECS/Entity.cs
`Entity.destroy()` indirectly modifies the child collection as it loops over it, which results in some children not being destroyed. One solution is to simply iterate over the list in reverse.
> Fix destroying entity not destroying all children

- Nez-PCL/PipelineRuntime/Tiled/TiledMap.cs
There used to be a comment here that said
> annoyingly we have to compensate 1 pixel per tile, seems to be a bug in MonoGame?
but I don't see anything indicating that this is still the case. Just `tile count * tile dimension` is giving the expected behavior.
> Fix TiledMap dimensions

- Nez-PCL/ECS/Components/Renderables/TiledMapComponent.cs
When TiledMapComponent creates its colliders, it offsets them based on the entity's position. However, colliders already account for the entity's position, resulting in the colliders being offset twice as much as they should be.
> Fix TiledMapComponent colliders being offset by entity position twice

- Nez-PCL/PipelineRuntime/Tiled/TiledObject.cs
I'm not sure if this jives with the philosophy for Nez, but I noticed when using a `TiledObject`, if I needed to make an entity I'd often do this - 
```
createEntity("name", new Vector2(tiledObj.X, tiledObj.Y));
```
I added a little property in the TiledObject class that adds position, so I can then easily type
```
createEntity("name", tiledObj.position);
```
Edit: Not sure what's going on with my tabs, Github keeps changing them on me :pensive:  In the edit view/Files changed window it looks fine but in the commits they're misaligned.  Sorry about that.
> Tiled object helper property

- Nez-PCL/ECS/Components/Renderables/Sprites/SpriteAnimation.cs
`_hasBeenPreparedForUse` was replaced with `_isDirty` and the checks in `prepareForUse()` were negated, but the initial value was not negated as well, causing the sprite animation to not be prepared for use.
> Fix sprite animation not being prepared for use

- Nez-PCL/UI/Widgets/SelectBoxList.cs
For taller SelectBoxes than ones that are created with the default skin (tested on 43 pixels tall), on its update the condition governing whether the list should hide again was fulfilled when it shouldn't have been, resulting in the SelectBox immediately hiding its list after opening if you clicked more than halfway up. On a 43-px tall one, that's pretty much the magic 20 that was here.
This behaviour doesn't appear with a dropdown having the default skin, and I suspect it's because it was shorter than 20 pixels.
> Fix to errant selectBoxList closing

- Nez-PCL/UI/Base/Group.cs
Groups could show unexpected behaviour if the x/y changed during the draw calls. This could be seen with two dropdowns side by side - click one dropdown to open it, and then next click the other dropdown, and the second list would be shown in the same place as the first was.
This change keeps any changes from draw calls, but still removes the offset. This seems to have resolved the issue.
> Group x/y fix

- Nez-PCL/UI/Widgets/Dialog.cs
Dialog.show will throw a NullReferenceException when it gets to Window.keepWithinStage - it goes there because it gets moved to the center of the stage, but at that point there's no stage for keepWithinStage to use.
> Dialog show fix

- Nez-PCL/ECS/Scene.cs
This PR adds `SceneResolutionPolicy.BestFit` which works somewhat like `ShowAll` except that a "bleed area" can be defined where cropping will occur if necessary (if both horizontal and vertical bleed size is set to 0 then it behaves exactly as `ShowAll`).
Advantage of this resolution policy is that you can, for example, set you design size to 1348x900 and define bleed areas of 148x140 (so that's 74px from left and right, and 70px from top and bottom edge) and basically you cover 3:2, 16:10, 16:9, 4:3 and 5:3 resolutions without any pillar or letter boxing (and those are most common aspect-ratios in use today across all devices). You just have to keep all your interactive components inside of a safe area (so in this example that's 1200x760 rect in the center) and fill the "bleed area" …
> Implement BestFit scene resolution policy

- Nez.Portable/Graphics/DeferredLighting/Lights/PointLight.cs
The bounding rectangle of the point light wasn't centred on the entity. Instead, it was anchored by the top-left corner. This caused lights to visibly turn on/off when the entity went in/out of the camera area.
> Fixed bounds not matching actual light area

- Nez.Portable/Utils/DebugConsole/DebugConsole.cs
I have been hacking `Nez.Samples.DestructableTilemapScene` and noticed that a custom Nez console command declared in Nez.Samples assembly is not registered.
Further debugging showed that method `Nez.Console.DebugConsole.buildCommandsList` has an error.
> System.AppDomain.CurrentDomain.GetAssemblies invocation fix

- Nez.Portable/Graphics/Transitions/SceneTransition.cs
This is an Action, in which when a Transition has completed it's work, and cleaned up after itself, onTransitionCompleted() can be called, so that other work can be executed after the transition.  Such as creating a new transition to execute, this allows for Intro splash screens with multiple screens to be created.
> Feature onTransitionCompleted()

- Nez.PipelineImporter/LibGdxAtlases/LibGdxAtlasWriter.cs
- Nez.Portable/Graphics/Textures/NinePatchSubtexture.cs
- Nez.Portable/PipelineRuntime/LibGdxAtlases/LibGdxAtlasReader.cs
- Nez.Portable/UI/Drawable/NinePatchDrawable.cs
Updated LibGdxAtlasWriter.cs to properly handle Writing out the Padding information to the .xnb file.
Updated LibGdxAtlasReader.cs to properly read the values out of the .xnb file
Updated NinePatchSubtexture.cs to handle Padding information, With padLeft being null, to determine if padding information is available.
Updated NinePatchDrawable.cs to properly use padding information if available, otherwise use the split as the padding information.
This patch confirmed to work, but requires that XNB Content to be re-compiled, as LibGdxAtlas content has been changed.
> NinePatch Padding handling

- Nez.Portable/PipelineRuntime/Tiled/TiledIsometricTiledLayer.cs
In my own game it came up that I needed subpixel movement to avoid some sprite jittering, so I scaled all the graphics by 2x so I could move sprites with finer granularity (different to regular resolution policy scaling). In order to do that I needed native scaling support in in Nez isometric tiledmaps, so added. :)
> Added ability to scale a tiledmap isometric tile

- Nez.Portable/UI/Widgets/Label.cs
When the Label instantiated with text or it's text set via `setText` method it marks as invalidated and it's `_wrappedString` field set null. But only part of the code which set's the `_wrappedString` other than `null` is `computePrefSize` method, which is only called in `preferredWidth` and `preferredHeight` getters, and only the `preferredHeight` getter is accessed in `layout()` method but only in if `setWrap` called.
> Fix Label preferred size is not calculated

- Nez.Portable/Debug/Assert.cs
For when you just know it's gone wrong.
Avoids having to use constructs like `Assert.isTrue(false, "It's all gone wrong");`
> Add fail() assert methods

- Nez.Portable/ECS/Camera.cs
- Nez.Portable/Input/Input.cs
- Nez.Portable/Input/TouchInputUtils.cs
For discussion. Add support for projecting touch positions in to world space.
Extracts scaling algorithm in to a separate method in Input.
Adds scaledPosition method to TouchLocation (like scaledMousePosition).
Adds touchToWorldPoint method to Camera.
> Add conversion of touch input positions to world coordinates

- Nez.Portable/ECS/InternalUtils/EntityList.cs
- Nez.Portable/ECS/Scene.cs
Currently the naming of `Scene.findObjectOfType<T>` is a little ambiguous, since, compared to `Scene.findEntityOfType<T>` which checks for `T : Entity`, checks for `T: Component` instead.
> Rename findObject to findComponent

- Nez.Portable/Nez.csproj
- Nez.Portable/Utils/Extensions/GestureSampleExt.cs
Matches changes in  @9ea6a943772b38b66b912362a730b9ec85a2698e but for `GestureSample`
Adds `scaledPosition` and `scaledPosition2` extension methods.
> Add conversion of touch input positions to world coordinates for gestures

- Nez.Portable/UI/Widgets/TextField.cs
For the moment if we increase the Height of the TextField, it'll render the text/selection/cursor at the very top, it is not the right behavior for a TextField (probably for a TextArea)
This commit fix the rendering position, if the height of the widget is larger than the height of the text, it'll apply an yOffset
Before:
After:
> Fixed TextField rendering position

- Nez.Portable/ECS/Camera.cs
The reason for this change is that my gameplay area is only a portion of the window, the rest is composed of status panels and whatnot. But the way Camera bounds are calculated right now is hardcoded to use the entire viewport. So if I want to cull map tiles outside of the playable area, and for the FollowCamera to work correctly for me, I need to be able to define a custom bounding rectangle for the camera.
If there's a better way to do this, let me know. I made sure that the default is still set to the viewport, so it shouldn't break any existing usages.
> added setInset fluent method to inset camera bounds

- Nez.Portable/ECS/Components/Text/MarkupText.cs
Just a quick fix, I noticed the `MarkupText` was rendering always in the same position regardless the value of the local offset. Fix based on the `render` method of the `Text.cs` (transform position plus local offset): https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Text/Text.cs#L146
> Consider LocalOffset when rendering the MarkupText

- Nez.Portable/ECS/Components/Renderables/Mesh.cs
When dynamically updating a mesh's verts, the bounds are not recalculated when calling recalculateBounds().  This fix sets them as dirty, so that the bounds will get recalculated lazily the next time they are accessed in the bounds prop.
> Mesh.recalculateBounds() now causes the bounds to be recalculated.

- Nez.Portable/ECS/Components/Renderables/Mesh.cs
TriangleStrips are nicer than TriangleLists because the triangle indices don't need to be calculated.  Many modeling programs export data as strips.
The primitive count (number of tris) in a triangle strip is `_verts.Length - 2`. 
3 verts are 1 triangle (first triangle is vert 0, 1, 2)
4 verts are 2 triangles (the second triangle is vert 1, 2, and 3)
This PR keeps the current default functionality of Mesh to use TriangleLists, and adds a new function `Mesh.setPrimitiveType(PrimitiveType)`  If the primitive type is set to strips, then the cheaper DrawUserPrimitives call is made which sends less data to the GPU.
> Adding support for PrimitiveType.TriangleStrip in Mesh

- Nez.Portable/UI/Stage.cs
I refactored the Stage.update() function into several separate functions and enabled multi-touch by iterating through touches.
`Stage.update()` now calls `.updateInputMouse()` and `.updateInputTouch()`
These two functions call `.updateInputPoint()`
`.updateInputPoint()` figures out if its a Down, Up, or Move event and calls `.updateInputDown()`, `.updateInputMoved()`, or `.updateInputReleased()`.
I've tested it extensively to make sure the following events fire:
- ✅ onMousePressed
- ✅ onMouseMoved
- ✅ onMouseUp
- ✅ onMouseEnter
- ✅ onMouseExit
On these platforms:
- ✅  PC Monogame 3.5
- ✅  PC FNA latest
- ✅  Android Monogame 3.5
- ✅  Mac Monogame 3.5
- ✅  iOS 10
Also, since the code is split among smaller functions it's a bit easier to reason about the logic for the future.
This started …
> [UI] Refactored Ui.Stage.update() to allow multi-touch

- Nez.Portable/Utils/Screen.cs
This change is needed so that mobile can display in Portrait mode.
For example:
```c#
public Game1()
{
Screen.supportedOrientations =
DisplayOrientation.LandscapeLeft |
DisplayOrientation.LandscapeRight |
DisplayOrientation.Portrait |
DisplayOrientation.PortraitDown;
}
```
> Screen added DisplayOrientation to support portrait on Mobile

- Nez.Portable/Utils/Triangulator.cs
Fixes an out of range crash when the number of verts is > than the default 12.
Example:
``` c#
verts = new Vector2[28];
var triangulator = new Triangulator();
triangulator.triangulate(verts, true); // crash here
```
> Fix Triangulator for verts > 12

- Nez.Portable/ECS/Components/FollowCamera.cs
I'm adding the ability to specify the FollowCamera's CameraStyle on instantiation because it's unclear how to set it otherwise. 
Calling 'follow' right away is awkward because you have to specify the camera as a ctor parameter, which you normally don't need to, and you need to specify the same entity that you just used to new up the FollowCamera, which seems unnecessary.
And I made LockOn the default because that's the value '_cameraStyle' is set to when 'follow' is called from 'onAddedToEntity', which is how it's usually set. This is a different default than used in 'follow', but I don't want to risk changing the camera behavior of anyone's game that isn't going through the extra work to set it explicitly.
> added CameraStyle ctor parameter

- Nez.PipelineImporter/LibGdxAtlases/LibGdxAtlasWriter.cs
- Nez.Portable/PipelineRuntime/LibGdxAtlases/LibGdxAtlas.cs
- Nez.Portable/PipelineRuntime/LibGdxAtlases/LibGdxAtlasReader.cs
Support for animations in libGDX atlases, based on the index key which is -1 for standalone images and 0..n for animations. Due to the fact animations can be spread across pages using the sprite animations functionality from TextureAtlas was not possible.
**Note**: Breaks binary compatibility with existing content files due to writing region index to the file for each region.
> Added support for libgdx atlas animations

- Nez.Portable/Input/GamePadData.cs
There was a bug where the `...UpPressed()` and `...RightPressed()` methods for the left thumbstick of a gamepad had its checks against the deadzone backwards. This resulted in the method acting like a "released" check instead of a "pressed" check.
This fixes that issue by correctly checking against the deadzone.
> Fixes the Pressed method for up and right on the left thumbstick

- Nez.Portable/UI/Containers/Container.cs
'setBackground' in Container did not match the other overload by returning the Container object.
> made setBackground method fluent

- Nez.Portable/PipelineRuntime/Tiled/TiledTile.cs
Change:
make `tileset` property of TiledTile public.
This is necessary for custom tilemap generation, like requested in #268
> make tileset property of TiledTile public

- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimation.cs
Wanted to make a modified Sprite\<TEnum\> but it depended on these internal properties, I figure they're worth exposing for general use.
> Made internal SpriteAnimation properties public

- Nez.PipelineImporter/Tiled/TiledMapWriter.cs
- Nez.PipelineImporter/Tiled/TmxTileset.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledMap.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledMapReader.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledTileSet.cs
So there's an issue with the way the PipelineImporter is currently reading Tiled maps.
What happens is, Tiled disregards part of the tileset image that does not consist of evenly-sized tiles. For all intents and purposes let's assume that we have a tileset with 30px of tile height and width. If the tileset image is 160px wide this only leaves room for 5 tile columns (5 x 30 = 150) and the remaining 10px are actually ignored by Tiled.
Now all this is probably intended, but what happened to me when trying to import such a map is that the reader actually mistook that extra space off the edge as a tile since it had not yet reached its `x < texture.Width - margin` clause. But since we just assigned an id to the non-existing tile, we are now one id behind Tiled's id accounting, per row. So …
> Fixed Tiled importing issue

- FAQs/UsingMonoGame3.6.md
We are seeing a lot of questions about how to use Nez with MonoGame 3.6. This FAQ gives simple instructions to tweak Nez to run on MonoGame 3.6.
> Add an FAQ on using MonoGame 3.6

- Nez.Portable/Physics/SpatialHash.cs
Use consistent floor method in linecasting to avoid an edge case where the start and end are in the same voxel but are floor()'ed to different integers, causing an infinite loop.
> Fix infinite loop in linecast

- Nez.Portable/Physics/Shapes/ShapeCollisions/ShapeCollisionsLine.cs
For line segments that are vertical, the first calculation results in a
division by 0, which is Infinity. The resulting RaycastHit is never set
up properly.
> Handle vertical lines in ShapeCollision.lineToPoly.

- Nez.Portable/ECS/Components/Physics/Colliders/Collider.cs
> Make collider transforms dirty on enable in case parent has moved.

- Nez.Portable/ECS/InternalUtils/EntityList.cs
- Nez.Portable/Utils/Collections/FastList.cs
I noticed that list sorting was one of a couple causes of slowdowns within my game. There are two places that the entities within this class are sorted, one uses FastList<T> and the other uses List<T>. It was the second one that was causing the slowdown. So I switched the entity tag dictionary to also use FastList<T>, which made my test case go from ~6.5 seconds to a little over 4.
> Switched entity dictionary to use FastList for for faster sorting.

- Nez.Portable/UI/Widgets/Window.cs
Code that was supposed to check if the window title had been clicked (to ignore hits on elements under it) was totally whacky and was instead causing hits to be ignored when the window's x position was less than its width.
Resolves #284.
> Fixed incorrect window title click check

- Nez.Portable/ECS/Components/FollowCamera.cs
I hope this is the right way to fix this issue, but it seems that the FollowCamera deadzone isn't referencing the zoomed camera bounds, which breaks it when the zoom level is different from the render target.
Resolves #294.
> FollowCamera doesn't use zoomed camera bounds

- Nez.Portable/ECS/InternalUtils/EntityList.cs
Resolves #347.
Test case:
~~~
public class GameScene: Scene
{
public override void initialize()
{
var test = createEntity( "test" );
test.tag = 1;
}
}
~~~
Found 2 separate bugs that were preventing this from working.
The immediate bug was Entity::setTag() would call EntityList::removeFromTagList(), when the tag didn't exist yet, throwing a no key found exception.
After fixing that I also found that EntityList::addToTagList() would get called twice (once in setTag, and a second time in EntityList::updateLists() when processing a new entity. The double checking appears correct as it does cover off the 2 use cases (changing a tag before/after adding an entity), but it just happens to overlap if the entity is yet to be processed. Simple resolution was to remove the assert and have it silently …
> Fixed setting an entity's tag after adding it to a scene

- Nez.Portable/ECS/Components/Text/MarkupText.cs
if want to check if there is just one word, then need to check words.Length not wordRunSize
> Wrong value for checking if there is only one word

- Nez.Portable/Physics/SpatialHash.cs
This allowed me to use the "check overflow" functionality for debug builds. There may be more of these issues, though. See #211.
Also took me an embarrassingly long time to prepare this PR. I'm not used to working with either GitHub or git. :disappointed:
> fix #211: do not throw exception on hash key overflow

- Nez.Portable/Graphics/Effects/EffectResource.cs
Resolves #292 and builds on @nhorne's PR (#270). Missing piece was to use [Stream.CanSeek](https://msdn.microsoft.com/en-us/library/system.io.stream.canseek.aspx) to determine if the workaround is necessary.
> Fixed getFileResourceBytes NotSupportedException exception

- Nez.Portable/ECS/Components/Physics/TiledMapMover.cs
Resolves #323.
Previously horizontal collisions were disregarded while standing on a slope, which allowed a TiledMapMover to slide up a slope without getting stuck on tiles beneath/adjacent to the slope. 
Side view example:
█
█◣
██◣←☺
█☺
█◣
██◣
However, collisions with walls which **should** block motion were also disregarded while standing on a slope resulting in glitchy behavior wherever a slope met a wall. That is, an entity could move in and out of the wall every other frame, or pass into or through solid tiles.
This change reduces the disregarded horizontal collisions while standing on a slope to only tiles on the same row as a slope.
> Fixed TiledMapMover collision with walls while on a slope

- Nez.Portable/ECS/Components/Physics/TiledMapMover.cs
The getHighestSlopeEdge() function returns Edge.Right by default (for non-slopes) which lead to slightly staggered one way platforms causing characters to pop to the top when just walking left on the lower platform as referenced in #331.
> Collision fix for one way platforms which are slightly offset

- Nez.Portable/UI/Widgets/ProgressBar.cs
- Nez.Portable/UI/Widgets/Slider.cs
Changes with my reasoning behind them:
- Changed _min and _max into automatic properties (public getter, protected setter), added public properties for stepSize and value, added setMinMax() method --- I needed to both check and change those values in my project, and I believe having setter for min/max is better than creating new Slider each time I need to change min/max.
- Added parameter (bool, false by default) for setValue() that when true is going to ignore snapping values --- there was no reason to set value to anything (within min/max range) by manually calling setValue(), because snapping could only be avoided when holding shift.
- Reversed condition inside setValue() --- I believe that it's easier to understand, especially with another bool in there.
- When not snapping we first …
> Changes to ProgressBar.

- Nez.Portable/Debug/Inspector/Inspectors/FloatInspector.cs
- Nez.Portable/Debug/Inspector/Inspectors/Vector2Inspector.cs
This change was made to make those inspectors useable when used on a system with comma as default decimal separator.
> Made FloatInspector and Vector2Inspector use CultureInfo.InvariantCulture for float .ToString() and .TryParse() method calls.

- Nez.Portable/UI/Stage.cs
This change was made to make touch input position match screen position of UI elements when using scene design resolution other than actual screen size.
Conditions for touch position scaling are the same as conditions for mouse position scaling.
> Added touch input position scaling inside Stage.

- Nez.Portable/Input/Clipboard.cs
- Nez.Portable/Nez.csproj
SDL seems to be the best cross platform way to do this, and it also uses Monogame's dllmap and SDL libraries so no external dependencies are needed.
> Crossplatform clipboard implementation.

- Nez.Portable/ECS/Components/Renderables/Particles/ParticleEmitter.cs
Added pauseEmission() and resumeEmission() - they set `_emitting` to false or true. Resuming does have an additional check if stop() was called or duration reached, resulting in early return without change of value.
I added those methods because I couldn't find a way to stop emission while updating existing particles (not counting changing ParticleEmitterConfig.emissionRate to 0, because this is going to cause issues when using the same config across several emitters, especially if we want to pause only some of them).
Added isEmitting property - with addition of pausing and resuming emission, access to `_emitting` is going to be useful.
Added events are onAllParticlesExpired (called when particle count reaches 0) and onEmissionDurationReached (called when emission is stopped due to …
> Made it possible to pause particle emission without stopping existing particles, added events to emitter.

- Nez.Portable/ECS/Components/Renderables/Sprites/Sprite.cs
Without this change, originNormalized feels counter-intuitive to me.
If, for example, I set scale to Vector2(5f, 5f) then if I want to position that Sprite in the center I must use Vector2(0.1f, 0.1f) if I want origin to be in the middle. With this change the center is always going to be position Vector2(0.5f, 0.5f).
> Made Sprite originNormalized and setOriginNormalized scale with entity.transform.scale

- Nez.Portable/ECS/Components/Renderables/Sprites/PrototypeSprite.cs
PrototypeSprite doesn't work with #376.  It tries to set originNormalized to (.5,.5) in the constructor and has a null reference to entity.  I moved this to an onAddedToEntity override.
> Fix for #376 breaking PrototypeSprite

- Nez.PipelineImporter/Tiled/TiledMapWriter.cs
- Nez.PipelineImporter/Tiled/TmxObject.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledMapReader.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledObject.cs
This changes the pipeline to read the correct attribute for getting a TiledObject's unique identifier and corrects the field names because gid has a different meaning in Tiled. 
#387
> Use id attribute instead of gid in TiledObject

- Nez.Portable/Physics/Collisions.cs
This fixes a problem where the Cohen–Sutherland algorithm determines the circle center is inside the rectangle, but the rectangle center may not be in the circle when the rectangle is larger.
> Fix collision check for rect to circle

- Nez.Portable/Input/Input.cs
Trying to make a 10-player game but when I set Input.maxSupportedGamePads to 10, it would always reset to 4.
Tested with 6 game pads in a cross-platform Monogame project.
> fix: max gamepad count should be limited to the platform

- Nez.Portable/UI/Widgets/TextField.cs
as parentAlpha is set to 1 by stage the fonts alpha was messed up. For example setting font color to black turned font invisible and setting font color to orange set the font yellow.
> TextField font parentAlpha fix

- Nez.Portable/UI/Base/Group.cs
It fixed a weird bug i had (padding was ignored in some cases)
And looks like it is set to true by default in libGDX too: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/Group.java#L42
> Group transform true by default

- Nez.Portable/Math/Mathf.cs
Methods that got radians version are:
- float lerpAngle( float a, float b, float t )
- Vector2 rotateAround( Vector2 point, Vector2 center, float angleInDegrees )
- Vector2 pointOnCircle( Vector2 circleCenter, float radius, float angleInDegrees )
I've tested all new methods and compared them to their degree versions. There were no issue that I found. There were slight differences by very small float values, around 0.001f or less.
> Added additional method variations using radians instead of degrees in Mathf

- Nez.PipelineImporter/TextureAtlasGenerator/TextureAtlasProcessor.cs
Added a field for selecting a color that will be treated as transparent, as well as a field that says whether to use the color key at all (defaults to false.)
Uses ColorKey code from MonoGame.TextureProcessor on each texture found in the atlas.
> ColorKey support in TextureAtlasProcessor

- Nez.PipelineImporter/Tiled/TiledMapWriter.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledMapReader.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledObject.cs
I think support for `gid` ("global id") was removed by mistake when someone added the `id` field. The reference to it was still in TmxObject so was just a matter of me adding the missing read/write calls.
> Fixed regression that removed gid from TiledObject

- Nez.Portable/ECS/InternalUtils/ComponentList.cs
When removing components, don't cache the initial _componentsToRemove.Count value.  Doing so means that if a component removes another component from the entity, it isn't traversed and later the components to remove list is cleared with the result that the removal is lost.
This allows components to remove other components which allows for a component hierarchy, or to allow components to build upon other components underneath the hood.
> Avoid caching _componentsToRemove.Count when iterating.

- Nez.PipelineImporter/Tiled/TiledMapWriter.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledMap.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledMapReader.cs
- Nez.Portable/PipelineRuntime/Tiled/TiledTilesetTile.cs
As part of the tiled file format, tileset tiles can optionally have a list of objectgroups. https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile In the Tiled editor, this is used for adding collision to tiles in the tileset editor, and most of the plumbing for this feature already existed in PipelineImporter, so this PR adds support for writing the tile objectGroups to the compiled xnb file and reading in the Pipeline runtime.
> Add support for importing tile objectgroups

- Nez.Portable/Debug/Inspector/Inspectors/Inspector.cs
The inspector was crashing when using the PascalCase branch, and changing these hard-coded fields to PascalCase fixed it for me. Never done a pull request before so hopefully I'm doing this right, haha.
> Fixed a few more hard-coded field names in the inspector

- Nez.Portable/ECS/Components/Text/TextRun.cs
- Nez.Portable/Graphics/Batcher/Batcher.cs
- Nez.Portable/Math/Mathf.cs
Addresses #501. The second parameter has been changed from another expression that can be passed in to a variable epsilon to compare to, with `Mathf.Epsilon (0.00001f)` being the default. All current usages of the method use 0 as the second parameter, so the current subtraction that's being done is meaningless.
> Cleaned up usages of WithinEpsilon()

- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
Hi,
Before Sprite<T> refactoring there was a `CurrentFrame` field. This field is essential for animation state machines, for example, jump animation may consist of a non-looped animation followed by a looped animation. In order to do this you can play the first animation, then check current frame in the update method, and if we are at the last frame, switch the animation.
> Added CurrentFrame field to SpriteAnimator

- Nez.Portable/Assets/SpriteAtlases/Loader/SpriteAtlasLoader.cs
- Nez.SpriteAtlasPacker/SpriteAtlasPacker/Exporters/AtlasMapExporter.cs
let sprite atlas use international decimal seperator,
multiply origin with actual size of texture
> SpriteAtlas problems with decimal seperator and origin

- Nez.Portable/AI/FSM/StateMachine.cs
- Nez.Portable/ECS/Components/Physics/Mover.cs
Added method for looking into a State Machine's states without having to use `.ChangeState<R>()` to reach them.
Also changed Mover's `CalculateMovement` to not be weird with multiple collisions. Added an advanced version of `CalculateMovement` to allow access to every collision.
> State Machine convenience & Mover Physics changes

- Nez.Portable/Assets/SpriteAtlases/Loader/SpriteAtlasLoader.cs
While trying to integrate the Project with android File.OpenText doesn't pick the Content path for assets. After going through the other components and solutions the best way to read throught stream would be using TitleContainer.OpenStream().
Tested on my device.
Working awesome.
> File.OpenText is replaced by TitleContainer.OpenStream().

- Nez.Portable/UI/Drawable/SpriteDrawable.cs
Image was not rendered because size was not set when SpriteDrawable created from Sprite.
> fixed UI Image size not being set

- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
So, `PingPong` animations are currently played as:
```
[A][B][C][C][B][A][A][B] .. 
```
This commit fixes it to :
```
[A][B][C][B][A] ..
```
I guess it could be written with an independent utility function though.
> Fixed PingPong animation #532

- Nez.Portable/ECS/Components/Physics/Colliders/Collider.cs
Even though the first collider was detected, the result outputed by the call was a negative one. (Collider is null)
> Fixed false collision result making the first result's collider null.

- Nez.Portable/ECS/InternalUtils/EntityList.cs
- Nez.Portable/ECS/Scene.cs
- Nez.sln
Previously when trying to find entity of type in the scene the following not generic which made the following inline statement difficult to read;
````
controller.Avatar =
Scene.Entities.EntitiesOfType<Avatar>().FirstOrDefault() != null ?
(Avatar) Scene.Entities.EntitiesOfType<Avatar>().FirstOrDefault() :
null;
````
Now we can simply do:
````
controller.Avatar = Scene.Entities.EntitiesOfType<Avatar>().FirstOrDefault();
````
> Let find object of type return generic list

- Nez.Portable/ECS/Components/Renderables/StencilLight.cs
Shader wants light position in screen space coordinates so we pass those.
Stops the light glow radius from moving away from the actual source as the
camera moves.
> Fix stencil lighting when camera is moving.

- Nez.Portable/ECS/Scene.cs
This prevents the scene from maintaining its orientation when the device orientation changes.
Without this change, if the device is in e.g. Portrait, and orients to Landscape, the scene keeps
filling the Portrait part of the screen.
> Scene will call UpdatePolicyScaler on orientation change

- Nez.Portable/UI/Containers/ScrollPane.cs
Changes the initial speed of  `ScrollPane` from `0.005f` (too slow) to `0.05f` (reasonable).
> UI: faster scroll by default

- Nez.Portable/UI/Widgets/Image.cs
The Image scales accordingly if "SetScale" is used. Before a image bigger than the "Image" Element was drawn.
> Make Image respond to scaling

- Nez.Portable/Utils/Extensions/ComponentExt.cs
`HasComponent` exists in `Entity`, and a lot of its analogous methods exist in `ComponentExt`. `HasComponent` was missing, so I added it.
> add HasComponent to ComponentExt

- Nez.SpriteAtlasPacker/SpriteAtlasPacker/SpriteAtlasPacker.cs
When packing a sprite atlas, with frames: `000.png, 001.png, 003.png...` I end up with a random animation order. I looked around, and as far as I can see, there's no way to explicitly influence the frame order. It looks like it depends only on the order returned by `Directory.GetFiles`. 
I'm guessing this is an implementation detail between e.g. .NET and Mono, or Win/Unix. Adding this OrderBy statement ensures the order, even if the runtime does not return ordered results.
(I'm noticing the issue on macOS + Mono 6.8 )
> Ensure frame order when packing a sprite atlas

- Nez.Portable/UI/Widgets/Image.cs
Since `Image.SetDrawable` modifies `drawable`, it should check `drawable` for being null, not `_drawable`.
> Fix a null argument check

- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
The tileset image is relative to the tsx file, not the tmx file, so when we erroneously pass in the tmx source folder it can't find the file if the tsx file is in a different folder than the tmx
See https://github.com/prime31/Nez/issues/585
> Issue 585 Fixed bug where TiledMapLoader was failing when tsx file and tileset image were not in the same folder as the tmx file

- Nez.Portable/ECS/Components/Physics/TiledMapMover.cs
make the `CollisionLayer` and `Map` settable fields mirroring those in [TiledMapRenderer](https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Renderables/TiledMapRenderer.cs#L22), as requested by #591
> make CollisionLayer and TiledMap settable

- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
- Nez.Portable/Assets/Tiled/Runtime/TiledRendering.cs
- Nez.Portable/ECS/Components/Renderables/TiledMapRenderer.cs
https://github.com/prime31/Nez/issues/594
This fixes a performance hit when not explicitly using SetRenderLayers.  The camera bounds are now passed in as well, just like when you render each layer separately.  
It seems like in other cases in RenderMap and RenderLayer functions in `TiledRendering.cs` , when rendering TmxImageLayer, TmxGroup, TmxObjectGroup we are not passing the camera bounds. Should we be passing the camera.Bounds here as well?
`				else if (layer is TmxImageLayer tmxImageLayer && tmxImageLayer.Visible)
RenderImageLayer(tmxImageLayer, batcher, position, scale, layerDepth);
else if (layer is TmxGroup tmxGroup && tmxGroup.Visible)
RenderGroup(tmxGroup, batcher, position, scale, layerDepth);
else if (layer is TmxObjectGroup tmxObjGroup && tmxObjGroup.Visible) …
> 594 fix tile rendering when no layers provided

- Nez.ImGui/Core/ImGuiManager.cs
I'm using .NET Core 3 and the property `UseShellExecute` is set to `false` by default (it's `true` by default in .NET Framework).
You can see it [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=netframework-4.8#property-value).
Because of that I had an "Application not found" exception.
With this change it works seemlessly on both framework.
> Fix open file on GitHub

- Nez.Portable/Utils/Tweens/Tween.cs
This adds the possibility to set the loops count for a tween to infinity. To do it:
```cs
int loops = -1; // any negative number
tween.SetLoops(type, loops);
```
- The loop count will be forced to `-1` if it's negative.
- The loops will be executed while the `_loops` value isn't `0`, just as before.
The [condition for triggering](https://github.com/Drarig29/Nez/blob/db6e7992ac6c9c15e9bffc70a694f92be32eb57e/Nez.Portable/Utils/Tweens/Tween.cs#L386) the `LoopCompleteHandler` remains unchanged, even in Ping-Pong mode:
- First, the loop count is forced to `-1`
- Then, it's multiplied by 2, we have `-2`
- The handler is triggered only when the value is `-4`, which corresponds to the "pong" (loop complete)
> Handle infinite loop for tweens

- Nez.Portable/ECS/Components/Renderables/Particles/ParticleEmitterConfig.cs
Changed the defaults for the color fields inside the config to have no variance at all and to just output the particle with no fading or random colors.
StartColorVariance was (255,255,255,255) so a random color was picked by default, now its (0,0,0,0)
FinishColor was (0,0,0,255) so it would slowly turn black.
FinishColorVariance was (0,0,0,255) so a random alpha was picked by default, now its (0,0,0,0)
> Default ParticleEmitterConfig Colors 1:1 Sprite

- Nez.ImGui/Nez.Monogame.Standard.ImGui.csproj
- Nez.Persistence/Nez.Monogame.Standard.Persistence.csproj
- Nez.Portable/Core.cs
- Nez.Portable/Nez.Monogame.Standard.csproj
There are currently project versions for FNA Standard, but not for monogame.
I have added projects for Nez Portable, ImGui and Persistence.
Monogame 3.8 uses .NET Core, and so requires .NET Standard libraries. This will make Nez compatible out-of-the-box.
I also fixed what I consider a bug (although it may be by design...).
When the first scene is loaded, `Scene.Begin()` is called **before** `Core.OnSceneChange()` and for every scene change after, `Scene.Begin()` is called **before** `Core.OnSceneChange()`. This will normally make very little difference, but in some cases it can lead to unexpected behaviour.
For example, if you create a scene, and add the following code inside `OnStart`:
`Core.GetGlobalManager<ImGuiManager>().RegisterDrawCommand(SomeDrawFunction);`
You would expect that …
> Add Monogame .NET Standard projects.

- Nez.ImGui/Inspectors/TypeInspectors/AbstractTypeInspector.cs
- Nez.ImGui/Inspectors/TypeInspectors/SimpleTypeInspector.cs
- Nez.ImGui/Inspectors/TypeInspectors/TypeInspectorUtils.cs
- Nez.Portable/Utils/Extensions/MemberInfoExt.cs
- Nez.Portable/Utils/ReflectionUtils.cs
When using `Nez` and `System.Reflection` in project files, compiler cannot disambiguate between the two definitions of `GetCustomAttribute<T>`. Rename the `Nez` definition to avoid collisions.
> Rename GetCustomAttribute to GetAttribute

- Nez.Portable/Debug/Console/DebugConsole.cs
No need to get a list of attributes with type CommandAttribute as any method will only have 1 command attribute per method. Also using generic version of method is more readable.
> Removed unnecessary steps in getting command attributes

- Nez.Portable/Utils/Time.cs
When dragging the game window on Windows 10, the game will stop updating. When the game resumes, `Time.DeltaTime` is a huge value, which can bork out the game physics. Setting a `MaxDeltaTime` to something like `1f / 60` or `1f / 30` allows us to keep this value under control.
> Add MaxDeltaTime to Time class

- Nez.Portable/Input/Input.cs
Add a couple useful functions for manipulating input. For example, currently if you call `SetCurrentMouseState()`  then you can't control values like `Input.MousePositionDelta`, which depend on the previous input state.
> Add SetPreviousMouseState and SetPreviousKeyboardState

- Nez.Portable/Utils/Tweens/RenderableColorTween.cs
Absent this, RenderableColorTween gets freed to Pool<ColorTween> where it would be pulled later by requests for color tweens. Then it would apply its tween value to the renderable and not the tween target.  I don't call base.RecycleSelf to avoid having the underlying ColorTween implementation try and free the tween.
> Adds recycle override to fix pool bug

- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteRenderer.cs
Improves code quality via showing intentions better.
example:
```
var spriteRenderer = Entity.GetComponent<SpriteRenderer>();
spriteRenderer.SetSprite(new Sprite(newTexture));
// vs
spriteRenderer.SetTexture(newTexture);
```
> Added setTexture function to SpriteRenderer

- Nez.Portable/Physics/SpatialHash.cs
When calling OverlapCircle, it wasn't checking to see if the circle overlapped the box, instead it was checking to see if the circle's bounds were overlapping it. Now it does the same check as it does for the other shapes.
> Added check to see if circle overlaps box

- Nez.Portable/Math/Random.cs
A useful function for game programming when direction is involved.
For example:
```
float wobble = 2f;
Vector2 point = new Vector2(10.1f, -14.3f);
Vector2 pointTransformed = point + Nez.Random.NextUnitVector() * wobble;
```
> Function for Random Unit Vectors

- Nez.Portable/UI/Widgets/ImageTextButton.cs
- Nez.Portable/UI/Widgets/Label.cs
- Nez.Portable/UI/Widgets/TextButton.cs
- Nez.Portable/UI/Widgets/Window.cs
Shifts the existing `_fontScaleX` and `_fontScaleY` fields from properties of a `Label` to properties within `LabelStyle`. This allows font sizes for labels, TextButtons, etc. to be set globally through the skin/style system.. Also exposes these new style fields on the style objects for UI elements that contain `Label`s as children (e.g. `TextButton`/`TextButtonStyle` and `Window`/`WindowStyle`).
This should partially resolve [Issue 600](https://github.com/prime31/Nez/issues/600) - it provides a style-level means of scaling text on `Label` and UI elements containing `Label`, but doesn't change anything about the `TextField` element. Could potentially do something similar with `TextField`, but there's no current scaling logic in that class so I left it alone for now.
Thanks for creating …
> Move Label fontScale fields into LabelStyle

- Nez.Persistence/Json/JsonEncoder.cs
Serializing an array such as
```csharp
class Example
{
public string[] MyArray = new string[5];
}
```
will throw an error in JsonEncoder on this line: https://github.com/prime31/Nez/blob/ce2405d0b6b9f94da5e34a6af22c03e27affc59f/Nez.Persistence/Json/JsonEncoder.cs#L262
For Arrays, `listType.GetElementType()` is needed instead to fetch the Array's element type. I've added a simple check to fix this.
Additionally, the encoder will crash on this line when attempting to save null elements in a list or array:
https://github.com/prime31/Nez/blob/ce2405d0b6b9f94da5e34a6af22c03e27affc59f/Nez.Persistence/Json/JsonEncoder.cs#L273
`obj` is null in this case, so I've added a simple null check to fix it.
> Fix errors when serializing an Array with JsonEncoder

- T4Templates/ContentPathGenerator.tt
As noted by @magruder85 in #704:
The ContentPathGenerator.tt trimmed 3 chars from the resulting Paths if run from the Root folder.
> ContentPathGenerator.tt can now be run from the root-folder instead of a sub-folder

- Nez.Portable/Assets/Tiled/Runtime/TiledRendering.cs
Removes 4x CS0162 'Unreachable code detected' warnings from the `Nez.Portable` project.
> Removes CS0162 'Unreachable code detected' warning

- Nez.SpriteAtlasPacker/README.md
- Nez.SpriteAtlasPacker/SpriteAtlasPacker.Console/ProgramArguments.cs
- Nez.SpriteAtlasPacker/SpriteAtlasPacker.Console/Properties/launchSettings.json
- Nez.SpriteAtlasPacker/SpriteAtlasPacker.Console/SpriteAtlasPacker.Console.csproj
- Nez.SpriteAtlasPacker/SpriteAtlasPacker.sln
- Nez.SpriteAtlasPacker/SpriteAtlasPacker/Exporters/AtlasMapExporter.cs
- Nez.SpriteAtlasPacker/SpriteAtlasPacker/Importers/AtlasMapOriginsImporter.cs
- Nez.SpriteAtlasPacker/SpriteAtlasPacker/Properties/launchSettings.json
- Nez.SpriteAtlasPacker/SpriteAtlasPacker/SpriteAtlasPacker.cs
SpriteAtlasPacker was using the default origin (0.5,0.5) for all the sprites added to atlas, not using the values changed by the user (e.g. to 0.5,1 in isometric game). Following changes use the original .atlas file and extracts the Origins for the sprites from the file, which is improving greatly workflow of adding new sprites to the game.
> Extending SpriteAtlasPacker by ability to preserve Origins

- Nez.Portable/Assets/Tiled/Runtime/Map.Runtime.cs
- Nez.Portable/Assets/Tiled/Runtime/TiledRendering.cs
Included support for hexagonal tiled maps (odd rows, pointy top)
Created using the great guide in https://www.redblobgames.com/grids/hexagons
> Added hexagon support for tiled maps

- Nez.Persistence/Json/JsonEncoder.cs
Fix for this issue:
```csharp
class Shape { 
int x; 
int y; 
}
class Rectangle { 
int width; 
int height; 
}
class ThingToSerialize 
{
// JsonEncoder currently serializes this as a Shape when using TypeNameHandling.Auto
Shape MyShape = new Rectangle(); 
}
```
> TypeNameHandling.Auto works now for object fields

- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
A recent update to Tiled (I think 1.8?) changed filed name "type" on an object to "class", breaking object loading that tries to parse that field for any maps saved with that version of higher.  Updated TiledMapLoader to support both so objects will parse correctly in both old and new versions of Tiled.
> TiledMapLoader fix for a recent update of Tiled that changed field name

- Nez.Portable/Assets/Tiled/README.md
The tiled example shown in the README.md file seems to be outdated. I've updated the README.md file so the example works.
> Updated Tiled rendering example to work

- Nez.Portable/ECS/Components/Physics/Colliders/Collider.cs
There are a couple of situations where a Collider will register itself with the physics system when it's disabled. This can cause phantom collisions, which has resulted in the acceleration of a certain programmer's descent into madness.
Example 1:
```cs
var collider = entity.AddComponent(new Collider());
collider.Enabled = false;
// later, once entity.Update() is called, the collider will be added to the entity's component list
// and RegisterColliderWithPhysicsSystem() is called, ignoring collider.Enabled
```
Example 2:
```cs
collider.Enabled = false;
// SetLocalOffset ignores collider.Enabled and re-registers it with the physics system.
collider.SetLocalOffset(Vector2.Zero); 
```
> Collider no longer registers with physics system when disabled

- Nez.Portable/ECS/Components/Physics/Colliders/BoxCollider.cs
- Nez.Portable/ECS/Components/Physics/Colliders/CircleCollider.cs
- Nez.Portable/ECS/Components/Physics/Colliders/Collider.cs
- Nez.Portable/ECS/InternalUtils/ComponentList.cs
- Nez.Portable/Physics/ColliderTriggerHelper.cs
Fixes an issue where when an Entity is enabled, it will call OnEnabled() on _all_ of its components, even those that are individually disabled. This appears to be a bug, as it's very counter-intuitive for Component.OnEnabled() to be called when the component is still disabled.
This behavior was causing a bug with the Collider class which can be reproduced as follows:
```cs
var collider = entity.AddComponent(new BoxCollider());
collider.Enabled = false;
// wait an update cycle
entity.Enabled = false;
// wait an update cycle
entity.Enabled = true;
// collider.OnEnabled() will then be called and the disabled collider will register itself to the physics system
```
(If it's desirable for a disabled Component to know when the entity is enabled, I'd propose adding an OnEntityEnabled() method to …
> More fixes for disabled Colliders

- Nez.Portable/UI/Widgets/Button.cs
Buttons can't be activated via mouse when they are disabled but input events will still trigger the OnClicked handler.
A pretty simple change, and I hope nobody is relying on this unexpected behavior, but I suppose they technically _could_.
> Don't activate buttons with gamepad when they are disabled.

- T4Templates/ContentPathGenerator.tt
The current `ContenPathGenerator.tt` template spits out a full path for assets in the root source folders:
```
class Content
{
public const string Cursor = @"C:\Users\user\GitHub\MyGame\MainProject\Content\cursor.png";
}
```
This is problematic because now references will not be portable. They should instead be relative. After making the change the generated file now prints the following for assets in the root source folder:
```
class Content
{
public const string Cursor = @"Content\cursor.png";
}
```
Tested on VS 2022 on Windows 11
> Use relative path for root assets

- Nez.Portable/Input/Virtual/VirtualAxis.cs
- Nez.Portable/Input/Virtual/VirtualIntegerAxis.cs
Adds a `bool JustPushed(int direction)` method and `int DirectionJustPushed` property to VirtualIntegerAxis, which function similarly to `VirtualButton.IsPressed`. 
Also adds repeating input support to VirtualIntegerAxis, which allows JustPushed to repeatedly fire when set up with the new `SetRepeat` methods -- this again functions the same as VirtualButton's repeating input.
These features are super useful for UI, i.e. navigating through menu options with a gamepad control stick.
> Add JustPushed and SetRepeat methods to VirtualIntegerAxis

- Nez.Portable/Assets/Tiled/Runtime/Map.Runtime.cs
The math for converting from the isometric tile space to world space was slightly off. I presume (Height - 1) was the original approach for centering the Vector2 on the tile, but it was causing the x coordinate to be off by 1. For worldY, I add an additional yOffset to center it, but it could be removed to set the point to the top left of the tile.
Here's a couple of images of the differences. The blue squares are walls, the orange ones are open tiles.
**Before**
**After**
> Isometric Tile To World Position Fix

- Nez.Portable/Utils/Extensions/ColorExt.cs
Previously, when using the ColorExt.HexToColor(string hex) static function, we had to make sure that the provided string does not start with a # sign. Additionally, if we wanted to parse a hex color string which contains details about the alpha channel, this would get overlooked. With this PR, these issues are fixed.
---
Had to close my previous PR due to some mixup with my branch. Hope this one works. 😅
> Support two new hex color string formats

- Nez.Portable/Graphics/Batcher/Batcher.cs
Resolves #761 
All I've done here is taken the destination rounding code from the Texture2D implementation of PushSprite and placed it in the Sprite implementation.
> Respect sprite rounding in both implementations of Batcher.PushSprite()

- Nez.Portable/Core.cs
- Nez.Portable/ECS/Entity.cs
I ran into an issue where a schedule destruction of an entity was causing a crash if the scene changed before the scheduled event fired.
This smells a little bit fishy, cause I would expect the entity to get destroyed on scene changed, or at least caught by the GC, and thus give an error that the target of the destruction is null. But instead I'm getting an exception saying that the Scene is null, implying that the entity is sticking around after a scene change.
If there's an underlying problem here then this PR does not fix that, but it does fix the one specific issue I had.
> Check if scene is null before destroying entity

- Nez.ImGui/README.md
The function `RegisterGlobalManager' is now in PascalCase and not camelCase as seen in the file [Core.cs](https://github.com/prime31/Nez/blob/a1cd7fc5d7ff9a205f89a87a6198b43dc09148b2/Nez.Portable/Core.cs#L405C38-L405C38)
> Fix outdated spelling for Core.RegisterGlobalManager in Documentation

- Nez.Portable/Assets/SpriteAtlases/SpriteAnimation.cs
- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
This adds the option to specify a framerate/delay per frame instead of a single framerate for an entire animation. This is in preparation for adding Aseprite support.
`for` loop is used to populate the array in the original constructor instead of `Enumerable.Repeat` because it's faster (Do I need to justify this?) and `++i` instead of `i++` since we don't need the copy. I believe compiler would optimize this anyway, so feel free to tell me to change it to `i++` if preferred.
> Added per frame framerate

- Nez.Portable/Assets/BitmapFonts/BitmapFontLoader.cs
I ran into a problem where a .fnt file I had generated could not be read by Nez, and I figured out the issue was that the generated file had no parameter for `padding` defined, I guess since I had set padding to 0, that specific program defaulted to not including the parameter at all. Nez should probably check if the padding parameter is there before trying to read from it.
> Check if font file has padding defined.

- Nez.Portable/UI/Stage.cs
Calling `SetGamepadFocusElement` with a target that already has gamepad focus causes focus to be lost.  This is because the function first puts focus on the new element, then unfocuses the previous element.  If they're the same element, the result is focus is dropped.
The fix is just to skip the focus/unfocus logic if the new target is the already focused element.  This is the same check that `SetKeyboardFocus` uses.
> Prevent SetGamepadFocusElement() from dropping focus when the target element already holds it

- Nez.Portable/ECS/Entity.cs
- Nez.Portable/ECS/InternalUtils/ComponentList.cs
Unity had removed the generic constraint a long time ago, and we can do the same. This way you can fetch a component by its Interface.
> allow Interfaces for GetComponent(s)

- Nez.Portable/Assets/Tiled/TiledTypes/TmxLayerTileExt.cs
appears to be an off-by-one mistake when using the tileWidth.
I noticed a few other places it might also be a mistake..
but I didn't get to test this fix myself. :p
> Fix bad math for Tiled sloped tiles

- Nez.Portable/Assets/Aseprite/Loader/AsepriteFileLoader.cs
Adds a `TryLoad` method to the `AsepriteFileLoader`.  When calling the underlying load method, when an exception occurs, this will output the exception details in the Debug panel and return `false` instead of causing exceptions to occur.
The reason for this PR is as follows
> Adds TryLoad Method to AsepriteFileLoader

- Nez.Portable/ECS/Scene.cs
Previously, `AddEntity` would add the entity's children to the scene while `AddEntity<T>` doesn't. This fixes that, and now `AddEntity` simply calls `AddEntity<T>` to ensure consistency.
> AddEntity(Entity) now calls AddEntity<T>(T) for consistency.

- Nez.Portable/Assets/Tiled/TiledTypes/Map.cs
Hello,
I loaded a TmxMap with some animated tiles. The number of allocated memory steadily increased.
After changing "foreach (var tileset in Tilesets)" to " for (var i = 0; i < Tilesets.Count; i++)" the allocated memory is stable.
It would be great if you could have a look at this issue and maybe allow to merge the pull request.
Best regards,
stallratte
> Object allocation of IEnumator caused memory leak

- Nez.Portable/Assets/Tiled/Runtime/TiledRendering.cs
- Nez.Portable/ECS/Scene.cs
Hello,
I added an ObjectLayer to a map in Tiled. The allocated heap memory increased steadily increased after adding the ObjectLayer to the layers to render.
The object allocation of IEnumerator (foreach-loop) in TiledRendering#RenderObjectGroup causes this issue. 
Here's a screenshot of the profiled memory which shows the memory growth after a few minutes:
With this fix the heap memory is stable.
Best regards,
stallratte
> RenderObjectGroup: Object allocation of IEnumator caused memory leak

- Nez.Portable/Assets/Aseprite/AsepriteSlice.cs
This resolves an issue when reading an `AsepriteSlice` that has user data.  Currently the `UserData` property is not initialized in the `AseprietSlice` constructor, which makes it `null` during the read process.
This change ensures the `UserData` property is initialized in the constructor for the `AsperiteSlice` class.
> Initialize UserData Property for AsepriteSlice

- Nez.Portable/Assets/Tiled/Runtime/Layer.Runtime.cs
- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
- Nez.Portable/Assets/Tiled/Runtime/TiledRendering.cs
- Nez.Portable/Assets/Tiled/TiledTypes/Layer.cs
- Nez.Portable/Assets/Tiled/TiledTypes/TmxLayerTileExt.cs
- Nez.Portable/ECS/Components/Physics/TiledMapMover.cs
Hello,
I'd like to create large maps in Tiled to e.g. have a town map which also contains the inside of buildings I can enter.
So I need larger maps. When I tried to load a larger map, I realized that it will need a lot of memory.
1. Every tile stores its x/y position. So every tile is unique
https://github.com/prime31/Nez/blob/0c16271e444d41e82e848feb03185bdae6f20e05/Nez.Portable/Assets/Tiled/TiledTypes/Layer.cs#L56-L58
2. CSV layers need lots of memory because of the strings created with Split(',')
https://github.com/prime31/Nez/blob/0c16271e444d41e82e848feb03185bdae6f20e05/Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs#L349
I tested the changes I made with a 1000 * 1000 tile (16x16) map with five tile layers. Now each layer needs ~4MB.
**Before**
**After**
Sadly this is a breaking …
> Tile layer memory consumption

- Nez.Portable/Assets/Tiled/Runtime/Layer.Runtime.cs
- Nez.Portable/Assets/Tiled/TiledTypes/Layer.cs
Optimo found a bug which was caused by the changes a made to the datastructure:
When trying to set a tile which already exists, a DuplicateKeyException is thrown. This is fixed now.
Because of the comment on the method:
> sets the tile and updates its tileset. If you change a tiles gid to one in a different Tileset you must call this method or update the TmxLayerTile.tileset manually!
I realized that there were two supported ways to replace a tile before my change:
1. Nez.Tiled.TmxLayer.SetTile
2. Get the reference of a TmxLayerTile and directly change Gid and manually update the Tileset if the gid is in a different tileset
The second way is now no longer possible. Using the second way will lead to unwanted behaviour.
Directly changing the TmxLayerTile also made it possible to change the …
> SetTile will no longer throw a DuplicateKeyException

- Nez.FNA.Core.sln
- Nez.FarseerPhysics/Nez.FNA.Core.FarseerPhysics.csproj
- Nez.ImGui/Nez.FNA.Core.ImGui.csproj
- Nez.Persistence/Nez.FNA.Core.Persistence.csproj
- Nez.Portable/Graphics/Batcher/GraphicsResource.cs
- Nez.Portable/Nez.FNA.Core.csproj
FNA has a set of `.Core.csproj` projects that allow it to run with dotnet core 7 (and in my case 8). This doesn't work with Nez because Nez depends on either `net471` or `netstandard2.0`. Both of which I could not get to work with dotnet core 8 (please tell me if there is a way to make this work).
This PR adds a `.FNA.Core` version of:
- `Nez.FarseerPhysics`
- `Nez.ImGui`
- `Nez.Persistence`
- `Nez.Portable`
Additionally I have added a define `FNA_GCHANDLE` to nez portable as a workaround for #804. This made Nez work with an FNA version younger than 6 months old, which is what I imagine most dotnet core people would use.
> Added support for FNA.Core

- Nez.Portable/ECS/InternalUtils/EntityList.cs
it will skip in the case UpdateInterval is set to zero, where it would normally error with the modulus operation on the next line. this patch does double-duty,  when UpdateInterval is set to zero it allows effectively pausing of Entity updates.
> fixes modulus error when UpdateInterval is set to zero - EntityList.cs

- Nez.Portable/Utils/Fonts/NezSpriteFont.cs
Currently the unexpected developer trying out Nez and drawing text, will probably try to use a `SpriteFont`. When using this, they are being given the error
```
SpriteFont is too locked down to use directly. Wrap it in a NezSpriteFont
```
When they then switch to `NezSpriteFont` they get an unimplemented error with no further action.
Joining the discord I found this response from prime31:
```
just dont use SpriteFonts. they are crap quality anyway. use bitmap fonts which give you a ton more control
```
So I decided to give the error message a new direction the developer can look into to solve their issue
> Give a better warning on FNA when using a NezSpriteFont

- Nez.Portable/AI/FSM/StateMachine.cs
I wanted to be able to use a runtime-resolved type for the generic part of of ChangeState<R>. The messy way is with some reflection and binding. Instead here I created a new method with the same name, but non-generic. You simply pass in the Type. 
I've redressed the existing method to call thru to the new method.
Also added a ChangeToPreviousState() method that does what it says by calling the new method with the PreviousType as its argument. As long as it's non-null type it will work, in any case returning the _currentState as State<T>.
> ChangeState non-generic method - TypeStateMachine.cs

- Nez.Portable/ECS/Components/Physics/TiledMapMover.cs
Issue was introduced with https://github.com/prime31/Nez/pull/797
x and worldPosition of GetNearestEdge were swapped. This caused issues when using slopes like getting stuck when walking left.
> TiledMapMover: tile.GetNearestEdge -> Swapped method parameters

- Nez.Portable/Assets/BitmapFonts/BatcherBitmapFontExt.cs
Was skimming through code the other night and this caught my eye. Despite that in probably nearly all cases the instance referenced would likely be the same, it seemed like the right thing to do :)
> Use parameter in bitmap font extension method

- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteRenderer.cs
Currently, when you have a sprite renderer with a non-zero localOffset, when the sprite is flipped it does not adjust that offset, causing a flipped sprite to be misaligned. 
This PR adds this adjustment so that when the image is flipped we multiply that part of the offset by -1.
> Updated sprite renderer render function to account for flipX and flipY when rendering

- Nez.Portable/Input/GamePadData.cs
- Nez.Portable/Input/Input.cs
Small PR to expose the `GamePadData` states to make it in line with Mouse and Keyboard Last/Current states & added helper methods. Most of the PR is just refactor to accomodate that, with the addition of three methods:
- In `GamePadData.cs` added `HasGamepadStateChanged`
- In `Input.cs` added `HasMouseStateChanged` and `HasKeyboardStateChanged`
> Exposed GamePadData Last/Current States & Added Last/Current State Helpers

- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
This PR addresses adding adding support for sub elements in the tiled `ParsePropertyDict` method by adding support for classes. What are tiled classes? https://doc.mapeditor.org/en/stable/manual/custom-properties/#custom-classes - they are used to add a set of properties at once, but don't work out of the box in Nez due to their sub-property nature.
Ensure your local version of Tiled supports classes (introduced in Tiled 1.9).
- Create a new Tiled project
- Hit control+shift+p to open the action search widget (likely command+shift+p on mac?)
- Search `Custom types editor`
- Add a class
- Give the class some properties
- Create a new tmx map and create an object, giving it the class as a property. Save this and load it into Nez.
The specific part of the TMX file we care about looks …
> Adding support for Tiled classes

- Nez.Portable/Utils/Extensions/ColorExt.cs
Adds support for argb color strings through an optional boolean whilst keeping original logic intact and the default behaviour.
- Pull latest changes
- Test with string that is ARGB - ex: `"#0ab100d4"`.
- Observe `ColorExt.HexToColor("#0ab100d4", true)` now returning `177 0 212 10` in line with an ARGB color string.
> Added support for argb strings

- Nez.Portable/Utils/Collections/Pool.cs
C# XML documentation does not seem to support `{@link #...}` style. Also this one was referencing `push` when `Pool.Free` was meant.
> Update Pool.cs documentation

- Nez.FarseerPhysics/Nez.FNA.Core.FarseerPhysics.csproj
- Nez.ImGui/Nez.FNA.Core.ImGui.csproj
- Nez.Persistence/Nez.FNA.Core.Persistence.csproj
- Nez.Portable/Nez.FNA.Core.csproj
Hello,
the current version of FNA.Core supports net8.0: https://github.com/FNA-XNA/FNA/blob/master/FNA.Core.csproj#L3
So I updated the TargetFramework version.
This would solve this issue: https://github.com/prime31/Nez/issues/840
Best regards,
stallratte
> FNA.Core: net7.0 -> net8.0

- Nez.Portable/Assets/Aseprite/AsepriteFile.cs
the GetTextureFromFrameNumber method was supposed to have this when we originally came up with it. corrected now by including the background layer; the resulting flattened texture is wholly complete - everything visible is included, as intended.
> Aseprite convenience method should include background layer

- Nez.Portable/Graphics/Transitions/SceneTransition.cs
_isNewSceneLoaded was 'internal'. This would limit it to only be accessible to SceneTransition subclasses inside the Nez assembly. We make it 'protected' so derived subclasses in one's own project assembly can access the field.
> Access _isNewSceneLoaded in 3rd-party SceneTransition subclasses

- Nez.Portable/Core.cs
Simply adds a public prop (getter) for the internal private field.
> Make Core.SceneTransition a public property

- Nez.Portable/Assets/NezContentManager.cs
This method will return a string from a file reader. It could be used for any text file, but is intended make for simple tracking of json assets.
> Add LoadJson method to NezContentManager

- Nez.ImGui/Core/ImGuiManager.Impl.cs
As a proposal to solve https://github.com/prime31/Nez/issues/854
This reorganizes the Unload() method: splitting the render target reset and the clearing of lists into two distinct methods now. Going with the idea that the clearing of the lists may only need to happen after an explicit scene change event.
maybe `ResetRenderTarget` could be more-appropriately named. lmk.
> ImGuiManager - split-up Unload into two methods

- Nez.Portable/Assets/BitmapFonts/BitmapFont.Drawing.cs
Follow up to PR [858](https://github.com/prime31/Nez/pull/858)
It's now a standalone method. 
No changes (= no map nullcheck) to the original method and completely optional.
It's a copy of the original method but there's no other way around that if the og method should not be changed / no additional nullcheck should be added.
@prime31 Could you please give me feedback if this PR is ok? If not, I'll try to create some kind of BitmapFontWrapper in my project so I can use this feature.
Usage:
```csharp
var source = new FontCharacterSource("This is a multicolored text");
Graphics.Instance.BitmapFont.DrawInto(batcher, ref source, new Vector2(100, 150),
Color.White, 0, Vector2.Zero, new Vector2(3f, 3f), SpriteEffects.None, 0, _colorMap);
```
> mutli colored bitmap font support (next try)

- Nez.Portable/Assets/Aseprite/AsepriteFile.cs
like the previous method to get a numbered frame..
this method let's you specify the name of the aseprite tag to get a single frame from the start of an animation sequence.
> AsepriteFile - get texture from tagged animation

- Nez.Portable/Assets/Aseprite/AsepriteFile.cs
This new method calls through the original ToAtlas() for convenience. You supply a custom Vector2 origin to be applied to all the sprites in the generated atlas.
Ignore previous PR -fat fingered :\
> Set custom origin for Aseprite's generated atlases

- Nez.ImGui/Inspectors/SceneGraphPanes/PostProcessorsPane.cs
- Nez.ImGui/Inspectors/SceneGraphPanes/RenderersPane.cs
removing Renderer or PostProcessor entries from the inspector panes in ImGuiManager was only half functional before. And removing them twice cause exception. now the items are removed from the scene and the inspector lists are properly cleaned up
> ImGuiManager - fix removing Renderer/PostProcessor

- Nez.Portable/Assets/Aseprite/AsepriteFile.cs
- Nez.Portable/Assets/Aseprite/AsepriteFrame.cs
With these changes, the previous Aseprite.ToSpriteAtlas() will now have a new parameter for a layerName of type 'string', which gets defaulted to null. If user doesn't change it, then all the layers will be selected during animation creation (also depending on 'onlyVisibleLayers' parameter like before). An alteration in AsepriteFrame.FlattenFrame() was made to handle the provided layerName by AsepriteFile (if there is one).
Also, additional methods, one in AsepriteFile and AsepriteFrame (Aseprite.ToSpriteAtlasFromLayers() and AsepriteFrame.FlattenFrameOnLayers() respectively) were made so that user can add multiple layers as a parameter, in the form an array of strings. Example usage:
string[] layers = { "Player_Body_Layer", "Player_Armor_Layer" };
SpriteAtlas sprite = …
> Support for single-layer and multi-layer selection during SpriteAnimation creation based on an AsepriteFile

- Nez.ImGui/Inspectors/SceneGraphPanes/RenderersPane.cs
the Renderers panel in ImGuiManager was not including the afterPostProcessor renderers at all.
> add afterPostProcessor renderers to imgui panel

- Nez.Portable/Assets/BitmapFonts/BitmapFont.Drawing.cs
- Nez.Portable/Assets/BitmapFonts/BitmapFont.cs
I added a new DrawInto-method which directly draws an int.
I use it to create IntLabels. I think this method is pretty convenient, because it eliminates the need to convert an int to a string or having to work with a StringBuilder.
I also refactored the ColorMap-Method-Variant I recently added to avoid too much code duplication.
The original DrawInto-method is still untouched.
> New DrawInto-method which draws a number

- Nez.Portable/Graphics/Batcher/Batcher.cs
When using a UI element which enables scissor test like ScrollPane, memory consumption rapidly grows.
This is due to the fact that two new RasterizeState instances will be created on every Draw call: 
- https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Containers/ScrollPane.cs#L1289-L1291
- https://github.com/prime31/Nez/blob/master/Nez.Portable/Graphics/Batcher/Batcher.cs#L1044-L1052
In 90 seconds nearly 11000 instances (~1 MB) will be created.
To avoid this, I introduced a new field in the Batcher-class. So instead of creating a new instance of the class every time, only this field will be updated.
Do you have any concerns regarding this change or is there maybe a better solution to solve this?
I tested this change and didn't see any negative side effects.
> Scissor Test: Reduce memory consumption

- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
when a Tiled object is instantiated from a "tiled template" (more xml from an external .tx file, which Nez already supports), the 'Properties' node from the template node does get correctly consumed into the object.
However, near the end of the instantiation routine, the object-local 'Properties' node is loaded and this overwrites that entire template-loaded node. Ideally template values get loaded first and then object-local values merged into that.
So this code makes it do a merge-and-replace - template values are loaded first, then the object-local values are merged over those. Thus we have something closer to Tiled's 'spec' for how template fields are handled.
I've also relocated this logic a bit earlier to just after where the template values would get loaded, for better code …
> tiled object: merge properties dict with dict from template

- Nez.Portable/ECS/Components/Renderables/Sprites/SpriteAnimator.cs
The code that control the frames for the LoopMode.PingPong was being called twice.
This removes the first call, fixing the issue #878 .
> Remove duplicate PingPong animation code

- Nez.Portable/Utils/Extensions/KeysExt.cs
In Stage.UpdateKeyboardState(), key.GetChar() must return a value for _keyboardFocusElement.KeyPressed(key, c.Value) to be called.
Currently, Keys.Delete returns null, so KeyPressed() is not triggered for it. However, TextField's IKeyboardListener.KeyPressed() method checks for Keys.Delete:
var deletePressed = key == Keys.Delete;
Because KeyPressed() is never called, deletePressed is not set to true, and the Delete key doesn't work as expected in text fields.
This fixed the delete key not working in a TextField.
> Added Keys.Delete to GetChar() in KeysExt.cs

- Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs
TiledMapLoader successfully loads the 'Type' string of a TmxObject with a template on line 486: 
obj = new TmxObject().LoadTmxObjectFromTemplate(map, xDocTemplate.Element("template").Element("object"));
But this was not being checked before setting it to an empty string on line 509:
obj.Type = (string)xObject.Attribute("type") ?? (string)xObject.Attribute("class") ?? string.Empty;
This change prevents the correct Type attribute from being overwritten.
> Stopped TiledMapLoader from overwriting 'obj.Type' when loaded from a template

- Nez.Portable/UI/Stage.cs
My previous PR [#876 (Expanding Input)](https://github.com/prime31/Nez/pull/876/files)  updated the way that the stage accepts keys, but it used a newer language syntax. This ticket swaps the syntax used for the initialization in line with the rest of Nez, and should satisfy the requirements for https://github.com/prime31/Nez/pull/883 without changing the language version used.
> Updated Input Keys Initialization Syntax
